### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by TeslaHua** [Microsoft/LQ-Nets#11]
When I only have one GPU training, the following error occurs：

Traceback (most recent call last):
  File "cifar10-vgg-small.py", line 156, in <module>
    launch_train_with_config(config,trainer)
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/train/interface.py", line 90, in launch_train_with_config
    model.get_input_signature(), input,
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/utils/argtools.py", line 200, in wrapper
    value = func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/graph_builder/model_desc.py", line 92, in get_input_signature
    return [TensorSpec(shape=p.shape, dtype=p.dtype, name=get_op_tensor_name(p.name)[0]) for p in inputs]
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 4339, in get_controller
    yield default
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/graph_builder/model_desc.py", line 86, in get_input_signature
    inputs = self.inputs()
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/graph_builder/model_desc.py", line 117, in inputs
    raise NotImplementedError()
NotImplementedError

**Comment by EowinYe** [comment]
Try the branch [support-latest-tf-tensorpack](https://github.com/Microsoft/LQ-Nets/tree/support-latest-tf-tensorpack)

**Comment by TeslaHua** [comment]
I am using your latest code, my platform includes:
Ubuntu 16.04
TensorFlow-GPU-1.4.1
CUDA 8.0
Cudnn 6.0
Opencv 3.4.3
Tensorpack  0.9.4 

I only have one GeForce 1070 GPU, I can't run through your code, cifar10-vgg-small.py and imagenet.py can't run, report the same error NotImplementedError, is there any way to solve it?

**Comment by TeslaHua** [comment]
@EowinYe Thanks, but I am using your latest code, my platform includes:
Ubuntu 16.04
TensorFlow-GPU-1.4.1
Python3.5
CUDA 8.0
Cudnn 6.0
Opencv 3.4.3
Tensorpack 0.9.4

I only have one GeForce 1070 GPU, I can't run through your code, cifar10-vgg-small.py and imagenet.py can't run, report the same error NotImplementedError, is there any way to solve it?

**Comment by TeslaHua** [comment]
@EowinYe Thank you, it has been solved.

**Comment by xychenunc** [comment]
> @EowinYe Thank you, it has been solved.

Hi TeslaHua,

I have the same problem when running on a different model. How did you solve this problem?

Thanks
